default: &default
  adapter: postgresql
  encoding: unicode
  host: postgis
  port: 5432
  direct_port: 5432
  username: postgres
  password:

development:
  <<: *default
  database: carto_db_development
  conn_validator_timeout: 900
  connect_timeout: 2.5
  pool: 50
  prepared_statements: false

test:
  <<: *default
  conn_validator_timeout: -1
  connect_timeout: -1
  prepared_statements: false
  database: carto_db_test
