version: '3.7'

volumes:
  redis-data:
  postgis-data:
  postgis-extensions:

services:
  router:
    container_name: router
    build:
      context: docker/router
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cartodb
      - windshaft
      - sqlapi
      - postgis
      - redis
      - varnish

  cartodb: 
    container_name: cartodb
    build:
      context: docker/cartodb
    depends_on:
      - redis
      - postgis
      - sqlapi
      - windshaft
    environment:
      - CARTO_CARTODB_VERSION=${CARTO_CARTODB_VERSION}
      - CARTO_DEFAULT_USER=${CARTO_DEFAULT_USER}
      - CARTO_DEFAULT_PASS=${CARTO_DEFAULT_PASS}
      - CARTO_DEFAULT_EMAIL=${CARTO_DEFAULT_EMAIL}
      - CARTO_ORG_NAME=${CARTO_ORG_NAME}
      - CARTO_ORG_USER=${CARTO_ORG_USER}
      - CARTO_ORG_EMAIL=${CARTO_ORG_EMAIL}
      - CARTO_ORG_PASS=${CARTO_ORG_PASS}

  varnish:
    container_name: varnish
    build:
      context: docker/varnish
    depends_on:
      - sqlapi
      - postgis
      - redis

  windshaft:
    container_name: windshaft
    build:
      context: docker/windshaft
    depends_on:
      - redis
      - postgis
      - sqlapi
    environment:
      - CARTO_WINDSHAFT_VERSION=${CARTO_WINDSHAFT_VERSION}

  sqlapi:
    container_name: sqlapi
    build:
      context: docker/sqlapi
    depends_on:
      - redis
      - postgis
    environment:
      - CARTO_SQLAPI_VERSION=${CARTO_SQLAPI_VERSION}

  redis:
    container_name: redis
    build:
      context: docker/redis
    volumes:
      - redis-data:/data

  postgis:
    container_name: postgis
    build:
      context: docker/postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - postgis-extensions:/usr/share/postgresql
    ports:
      - "5432:5432"
    environment:
      - CARTO_PGEXT_VERSION=${CARTO_PGEXT_VERSION}
      - CARTO_DATASVCS_API_CLIENT_VERSION=${CARTO_DATASVCS_API_CLIENT_VERSION}
      - CARTO_DATASVCS_API_SERVER_VERSION=${CARTO_DATASVCS_API_SERVER_VERSION}
      - CARTO_DATASVCS_VERSION=${CARTO_DATASVCS_VERSION}
      - CARTO_ODBC_FDW_VERSION=${CARTO_ODBC_FDW_VERSION}
      - CARTO_CRANKSHAFT_VERSION=${CARTO_CRANKSHAFT_VERSION}
      - CARTO_OBSERVATORY_VERSION=${CARTO_OBSERVATORY_VERSION}
