version: '3.7'

volumes:
  redis-data:
  postgis-data:
  postgis-extensions:

services:
  router:
    container_name: router
    build:
      context: docker/router
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cartodb
      - windshaft
      - sqlapi
      - postgis
      - redis
      - varnish

  cartodb: 
    container_name: cartodb
    build:
      context: docker/cartodb
    depends_on:
      - redis
      - postgis
      - sqlapi
      - windshaft
    environment:
      - CARTO_USE_HTTPS=${CARTO_USE_HTTPS:-true}
      - CARTO_CARTODB_VERSION=${CARTO_CARTODB_VERSION}
      - CARTO_DEFAULT_USER=${CARTO_DEFAULT_USER}
      - CARTO_DEFAULT_PASS=${CARTO_DEFAULT_PASS}
      - CARTO_DEFAULT_EMAIL=${CARTO_DEFAULT_EMAIL}
      - CARTO_ORG_NAME=${CARTO_ORG_NAME}
      - CARTO_ORG_USER=${CARTO_ORG_USER}
      - CARTO_ORG_EMAIL=${CARTO_ORG_EMAIL}
      - CARTO_ORG_PASS=${CARTO_ORG_PASS}

  varnish:
    container_name: varnish
    build:
      context: docker/varnish
    depends_on:
      - sqlapi
      - postgis
      - redis
    tty: true

  windshaft:
    container_name: windshaft
    build:
      context: docker/windshaft
    depends_on:
      - redis
      - postgis
      - sqlapi
    environment:
      - CARTO_WINDSHAFT_VERSION=${CARTO_WINDSHAFT_VERSION}

  sqlapi:
    container_name: sqlapi
    build:
      context: docker/sqlapi
    depends_on:
      - redis
      - postgis
    environment:
      - SQLAPI_VERSION=${SQLAPI_VERSION}
      - SQLAPI_ENVIRONMENT=${SQLAPI_ENVIRONMENT}
      - SQLAPI_LISTEN_PORT=${SQLAPI_LISTEN_PORT}
      - SQLAPI_LISTEN_IP=${SQLAPI_LISTEN_IP}
      - SQLAPI_POSTGIS_HOST=${SQLAPI_POSTGIS_HOST}
      - SQLAPI_POSTGIS_PORT=${SQLAPI_POSTGIS_PORT}
      - SQLAPI_REDIS_HOST=${SQLAPI_REDIS_HOST}
      - SQLAPI_REDIS_PORT=${SQLAPI_REDIS_PORT}

  redis:
    container_name: redis
    build:
      context: docker/redis
    volumes:
      - redis-data:/data

  postgis:
    container_name: postgis
    image: osscarto-packer-postgis:latest
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - postgis-extensions:/usr/share/postgresql
    ports:
      - "5432:5432"
